#!/usr/bin/env node

var lunr = require('lunr'),
    stdin = process.stdin,
    stdout = process.stdout,
    buffer = []

stdin.resume()
stdin.setEncoding('utf8')

stdin.on('data', function (data) {
  buffer.push(data)
})

stdin.on('end', function () {
  var corpus = JSON.parse(buffer.join())

  var idx = lunr(function () {
    this.ref('id')
    this.field('name')
    this.field('body')

    // This is required to provide the position of terms in
    // in the index. Currently position data is opt-in due
    // to the increase in index size required to store all
    // the positions. This is currently not well documented
    // and a better interface may be required to expose this
    // to consumers.
    this.metadataWhitelist = ['position']

    // This is the biggest change to the interface over the
    // 0.x and 1.x branches. Documents must be added to the
    // index within this closure. When this function completes
    // the index is immutable, no more documents can be added.
    corpus.forEach(function (doc) {
      this.add(doc)
    }, this)
  })

  stdout.write(JSON.stringify(idx))
})
